-- MySQL Script generated by MySQL Workbench
-- vie 10 feb 2017 11:11:49 COT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escuela
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escuela` DEFAULT CHARACTER SET utf8 ;
USE `escuela` ;

-- -----------------------------------------------------
-- Table `escuela`.`carreras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`carreras` (
  `id_carrera` INT NOT NULL,
  `nombre_carrera` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_carrera`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`alumnos` (
  `no_control` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `ap_paterno` VARCHAR(45) NOT NULL,
  `ap_materno` VARCHAR(45) NOT NULL,
  `id_carrera` INT NOT NULL,
  PRIMARY KEY (`no_control`),
  INDEX `fk_alumnos_carreras_idx` (`id_carrera` ASC),
  CONSTRAINT `fk_alumnos_carreras`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `escuela`.`carreras` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`materias` (
  `clave_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre_materia` VARCHAR(45) NOT NULL,
  `id_carrera` INT NOT NULL,
  PRIMARY KEY (`clave_materia`),
  INDEX `fk_materias_carreras1_idx` (`id_carrera` ASC),
  CONSTRAINT `fk_materias_carreras1`
    FOREIGN KEY (`id_carrera`)
    REFERENCES `escuela`.`carreras` (`id_carrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escuela`.`calificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escuela`.`calificaciones` (
  `materias_clave_materia` INT NOT NULL,
  `alumnos_no_control` INT NOT NULL,
  `calificacion` DECIMAL(2) NOT NULL,
  INDEX `fk_calificaciones_materias1_idx` (`materias_clave_materia` ASC),
  INDEX `fk_calificaciones_alumnos1_idx` (`alumnos_no_control` ASC),
  PRIMARY KEY (`materias_clave_materia`, `alumnos_no_control`),
  CONSTRAINT `fk_calificaciones_materias1`
    FOREIGN KEY (`materias_clave_materia`)
    REFERENCES `escuela`.`materias` (`clave_materia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_calificaciones_alumnos1`
    FOREIGN KEY (`alumnos_no_control`)
    REFERENCES `escuela`.`alumnos` (`no_control`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
